version: '3.9'

services:
    nginx:
        build:
            context: ./docker/nginx
        restart: on-failure
        volumes:
            - '.:/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8080:80'
        depends_on:
            - php

    db:
        build:
            context: ./docker/mysql
        restart: on-failure
        volumes:
            - './docker/mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf'
        environment:
          - MYSQL_ROOT_PASSWORD=12345
          - MYSQL_USER=user
          - MYSQL_PASSWORD=12345
          - MYSQL_DATABASE=todo_list
        ports:
            - '3306:3306'

    php:
        build:
            context: ./docker/php
        volumes:
            - '.:/app'
            - './docker/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
        working_dir: /app
        environment:
            - PHP_IDE_CONFIG=serverName=todo-list.loc
        depends_on:
            - db