api_login_check:
  path: /api/login_check

api_login:
  path: /api/login
  controller: App\Controller\SecurityController::loginAction
  methods: POST

api_logout:
  path: /api/logout
  controller: App\Controller\SecurityController::logoutAction
  methods: GET

register:
  path: /register
  controller: App\Controller\RegistrationController::registrationAction
  methods: POST

api_todo_get_all:
  path: /api/todo
  controller: App\Controller\TodoController::getAllAction
  methods: GET

api_todo_get:
  path: /api/todo/{id}
  controller: App\Controller\TodoController::getAction
  methods: GET

api_todo_create:
  path: /api/todo
  controller: App\Controller\TodoController::createAction
  methods: POST

api_todo_edit:
  path: /api/todo/{id}
  controller: App\Controller\TodoController::editAction
  methods: PUT

api_todo_delete:
  path: /api/todo/{id}
  controller: App\Controller\TodoController::deleteAction
  methods: DELETE