#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

api_login:
  path: /api/login
  controller: App\Controller\SecurityController::loginAction
  methods: POST

api_logout:
  path: /api/logout
  controller: App\Controller\SecurityController::logoutAction
  methods: GET